#!/bin/sh

echo "\033[1;33mTesting Build\033[0m"
echo
./gradlew build -q
echo

RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "\033[1;31mBuild error please fix before you commit\033[0m"
  exit 1
fi

echo "\033[1;32mBuilt Successfuly!\033[0m"
echo

git add -u


exit 0
